# Generated by Django 2.2 on 2019-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirporInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude_deg', models.FloatField()),
                ('longtitude_deg', models.FloatField()),
                ('lvation_ft', models.IntegerField()),
                ('continent', models.CharField(max_length=2)),
                ('iso_country', models.CharField(max_length=2)),
                ('iso_region', models.CharField(max_length=10)),
                ('municipality', models.CharField(max_length=255, unique=True)),
                ('scheduled_service', models.BooleanField()),
                ('gps_code', models.CharField(blank=True, max_length=10, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=255, null=True)),
                ('local_code', models.CharField(blank=True, max_length=255, null=True)),
                ('home_link', models.URLField(blank=True, null=True)),
                ('wikipedia_link', models.URLField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
