# Generated by Django 2.2 on 2019-04-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirporInfo',
            new_name='AirportInfo',
        ),
    ]
